server:
  #port: 8002
  servlet:
    context-path: /
debug: true #是否Debug启动
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product
  datasource: #数据库连接
    username: SYSTEM
    password: 92960504
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl #jdbc:mysql://localhost:3307/orcl
    driver-class-name: oracle.jdbc.OracleDriver #com.mysql.jdbc.Driver
ribbon:
  eager-load:
    enabled:  true
    clients:  product