server:
  port: 8040
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #定义路由列表
  routes:
    eureka-server-static:
    api-a: #接口A 数据网关
      path: /api-data/** #前缀地址定义
      serviceId: product #后缀地址定义：服务名
      sensitiveHeaders: "*" #旧Session信息保留
    api-b: #接口B User视图网关
      path: /api-view/**
      serviceId: goodprovide,admin
      sensitiveHeaders: "*"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000