server:
  port: 8040
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #定义路由列表
  routes:
    eureka-server-static:
    #接口A
    api-a:
      #前缀地址定义
      path: /api-data/**
      #后缀地址定义：服务名
      serviceId: product
      #旧Session信息保留
      sensitiveHeaders: "*"
    #接口B
    api-b:
      path: /api-view/**
      serviceId: provide
      sensitiveHeaders: "*"